#!/bin/tcsh

set case   = $1
set curdir = `pwd`
set outdir = ../out

mkdir -p $case
mkdir -p $case/obj
mkdir -p $case/usr_beps
mkdir -p $outdir/$case

cp ../models_assim/* $case/obj
cp ../models_assim/esmf_wrf_timemgr/* $case/obj

mv $case/obj/beps_build_control  $case
cp ../bld/* $case/obj
chmod u+x $case/obj/Mkdepends

cd $case
cat >! beps_run << EOF
#!/bin/bash
#SBATCH -p v3_64
#SBATCH -N 1
#SBATCH -n 2
source /public1/home/sc30439/zhaoyq-netcdf/netcdf.sh
module load mpi/mpich/1.0.8
srun ./beps
EOF

chmod u+x beps_run
chmod u+x beps_build_control

